### ISSUE TITLE
Version number repeated

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-java#10]
* https://github.com/twingly/twingly-search-api-java/blob/c9de572c9e77db3c904381964fdc02cf41e5fde7/build.gradle#L8
* https://github.com/twingly/twingly-search-api-java/blob/c9de572c9e77db3c904381964fdc02cf41e5fde7/src/main/java/com/twingly/search/Constants.java#L10

Not sure if we can do anything about it, but we should investigate.

**Comment by xSAVIKx** [comment]
I don't think we can do anything with it.
Maybe, the only way would be creation of some .properties file with version in this property, so that Java will take version from property file and gradle also will do smth like that, if this is critical.

**Comment by walro** [comment]
This is not critical at all, we have the same problem in other clients.
