### ISSUE TITLE
Update Java client to Search API v3 [$50]

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-java#29]
Update the client to use the new [Blog Search API v3](https://developer.twingly.com/resources/search/).

Notable changes from the previous version of the Blog Search API are listed under https://developer.twingly.com/resources/search#changes-from-previous-version.

The ruby client was updated in https://github.com/twingly/twingly-search-api-ruby/pull/65, which can be used as help. Some XML fixtures can also be copied from there if needed.

If possible, try to keep all classes/methods/properties backwards compatible with the previous version of the client by marking methods as deprecated. Similar to what was done in the Ruby client.

**Comment by dentarg** [comment]
If you are considering solving this issue, you might be interested in also solving one or more of the following issues (they also have bounties from https://www.bountysource.com/)

* https://github.com/twingly/twingly-search-api-dotnet/issues/32
* https://github.com/twingly/twingly-search-api-php/issues/22
* https://github.com/twingly/twingly-search-api-python/issues/31

**Comment by dentarg** [comment]
@xSAVIKx interested in the bounty here? :)

**Comment by xSAVIKx** [comment]
@dentarg Yea, why not? :-)

**Comment by xSAVIKx** [comment]
@dentarg should we support both v.2 and v.3 API?

**Comment by jage** [comment]
Hi,

> @dentarg should we support both v.2 and v.3 API?

> Update:
> Looks like we should not. I'd bump version to 3.0.0 in order to follow the API version.

Correct, no need to keep v.2 support.

> Also, I'd need some API key to test changes, could you please send me one?

Oh, we should have documented it, but you can register for a free trial (full API access) at https://app.twingly.com/signup

**Comment by xSAVIKx** [comment]
I've submitted a PR with updates to the v3 API.

I'd also ask to increase the bounty if it is possible, cause I've also closed #28 with my updates in order to support compression.

Regards,
Yuri.
