### ISSUE TITLE
Build and upload to the central maven repository

### ISSUE THREAD

**Issue by jage** [twingly/twingly-search-api-java#4]
> In order for users of Maven to utilize artifacts produced by your project, you must deploy them to a remote repository. Many open source projects want to allow users of their projects who build with Maven to have transparent access to their project's artifacts. In order to allow for this, a project must have their artifacts deployed to the Central Repository.

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

#3 should be done first though.

**Comment by twingly-mob** [comment]
Some handy links: 

* http://central.sonatype.org/pages/ossrh-guide.html#deployment
* http://central.sonatype.org/pages/gradle.html
* http://zserge.com/blog/gradle-maven-publish.html
* http://yennicktrevels.com/blog/2013/10/11/automated-gradle-project-deployment-to-sonatype-oss-repository/

**Comment by walro** [comment]
> http://central.sonatype.org/pages/ossrh-guide.html#deployment

I've created our Sonatype account and submitted a ticket.

**Comment by walro** [comment]
> I've created our Sonatype account and submitted a ticket.

Forgot to report back here, but our ticket was accepted so now we are clear to upload.

**Comment by walro** [comment]
I have publish to Sonatype now and promoted the release. Waiting on Sonatype to activate the sync process.

**Comment by walro** [comment]
http://search.maven.org/#artifactdetails%7Ccom.twingly%7Ctwingly-search-api-java%7C1.0.0%7Cjar :)
