### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-java#5]
Implement a test suite with on-par coverage with our [Ruby implementation](https://github.com/twingly/twingly-search-api-ruby/tree/master/spec).

We use [VCR](https://github.com/vcr/vcr) for two tests: [one](https://github.com/twingly/twingly-search-api-ruby/blob/bac8e4a6e7335b9fd37b2c839ad151ac175ac488/spec/client_spec.rb#L97-L101) and [two](https://github.com/twingly/twingly-search-api-ruby/blob/38e1afcbad121f7f61d666a5df1e380f563fcd40/spec/query_spec.rb#L176-L181). It seems like the most obvious [Java port, βetamax](https://github.com/robfletcher/betamax), is not really maintained anymore and it's also dependant upon Groovy. Perhaps it's possible to achieve the same degree of coverage using one of the following tools:

* http://wiremock.org/
* https://github.com/dreamhead/moco
* http://www.mock-server.com/

**Comment by dentarg** [comment]
> It seems like the most obvious Java port, βetamax, is not really maintained anymore

That is changing (woho), from https://github.com/betamaxteam/betamax/issues/167#issuecomment-184848861:

> robfletcher and I have teamed up and are reviving this project. Expect a new version very soon. Closing...

**Comment by twingly-mob** [comment]
Closed by #6
